### ISSUE TITLE
Error while unmarshal offerStr to offer. 

### ISSUE THREAD

**Issue by maddygoround** [grantfayvor/hexcord-mediaserver#4]
I am getting an error at `json.Unmarshal([]byte(offerStr), &offer)`. Any reasons why it does not work?

**Comment by grantfayvor** [comment]
Hey @maddygoround Sorry for the late response. Notification got lost.

Confirm that offerStr is a valid JSON string of an offer object.

https://github.com/grantfayvor/hexcord-mediaserver/blob/856b3f879b972100023d7c50caf1f540d46c01ba/lib/webrtc.go#L22

**Comment by maddygoround** [comment]
Thanks. I am able to solve this. I was sending the base64 content of the offer.
